# source : https://www.geeksforgeeks.org/python/setting-up-docker-for-python-projects-a-step-by-step-guide/

# Use an official Python runtime as a parent image
FROM python:3.14.2-slim-trixie

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt 
RUN pip install fastapi>=0.115.0
RUN pip install uvicorn>=0.32.0
RUN pip install python-dotenv>=1.0.0
RUN pip install httpx>=0.27.0
RUN pip install pydantic>=2.9.0
RUN pip install requests

# Make port 80 available to the world outside this container (Optional, only for web apps)
EXPOSE 8001

# Run app.py when the container launches
CMD ["python", "-u", "main.py"]